"""Regenerate the plot and LaTeX fragments from the bundled spectrum.

Run this script after changing data.csv, the approximation break points, or the
integration implementation. Generated text intentionally uses modest precision
because the input spectrum was digitized from a plot and has no supplied
measurement uncertainty.
"""

from __future__ import annotations

import math
from pathlib import Path

from cosmic_ray_rate import (
    APPROX_BREAKS_EV,
    DEFAULT_CSV,
    Approximation,
    approx_rate_above_flat_km2,
    calibrate_piecewise_approximation,
    compare_formula,
    load_spectrum,
    make_comparison_plot,
    rate_above,
)


ROOT = Path(__file__).resolve().parent
APPROXIMATION_TEX = ROOT / "generated_approximation.tex"
RATE_TABLE_TEX = ROOT / "generated_rate_table.tex"
PLOT_PATH = ROOT / "rate_comparison.png"


def _plain_significant(value: float, digits: int = 4) -> str:
    return f"{value:.{digits}g}"


def _tex_number(value: float, digits: int = 4) -> str:
    if value == 0.0:
        return "0"
    exponent = math.floor(math.log10(abs(value)))
    mantissa = value / (10.0**exponent)
    rounded = float(f"{mantissa:.{digits - 1}f}")
    if abs(rounded) >= 10.0:
        rounded /= 10.0
        exponent += 1
    mantissa_text = f"{rounded:.{digits - 1}f}".rstrip("0").rstrip(".")
    if exponent == 0:
        return mantissa_text
    return rf"{mantissa_text} \times 10^{{{exponent}}}"


def _tex_energy(value: float) -> str:
    exponent = round(math.log10(value))
    if math.isclose(value, 10.0**exponent, rel_tol=1.0e-12):
        return rf"10^{{{exponent}}}"
    return _tex_number(value, digits=4)


def _write_approximation_fragment(approximation: Approximation) -> None:
    median, p95, worst = compare_formula(
        csv_path=DEFAULT_CSV,
        n_points=10_001,
        approximation=approximation,
    )

    cases: list[str] = []
    for index, exponent in enumerate(approximation.exponents):
        e0 = approximation.breaks_eV[index]
        e1 = approximation.breaks_eV[index + 1]
        r0 = approximation.rates_per_s_per_km2[index]
        closing = r"\le" if index == len(approximation.exponents) - 1 else "<"
        cases.extend(
            [
                rf"{_tex_number(r0)}",
                (
                    rf"\left(\dfrac{{E}}{{{_tex_energy(e0)}\,\mathrm{{eV}}}}"
                    rf"\right)^{{-{exponent:.4f}}},"
                ),
                rf"& {_tex_energy(e0)} \le E {closing} {_tex_energy(e1)}\,\mathrm{{eV}},",
                r"\\[1.0em]",
            ]
        )
    cases.pop()

    text = "\n".join(
        [
            "% Generated by generate_artifacts.py; do not edit by hand.",
            r"\[",
            r"R_{\mathrm{fit}}(>E) \approx",
            r"\begin{cases}",
            *cases,
            r"\end{cases}",
            r"\]",
            "",
            (
                "The fit was sampled at 10,001 thresholds uniformly spaced in "
                "$\\log_{10} E$. The resulting absolute relative errors were "
                f"median ${100.0 * median:.2f}\\%$, 95th percentile "
                f"${100.0 * p95:.2f}\\%$, and worst sampled value "
                f"${100.0 * worst:.2f}\\%$. These are sampled statistics, not "
                "global mathematical bounds."
            ),
            "",
        ]
    )
    APPROXIMATION_TEX.write_text(text, encoding="utf-8")


def _write_rate_table_fragment(approximation: Approximation) -> None:
    rows = [
        "% Generated by generate_artifacts.py; do not edit by hand.",
        r"\begin{center}",
        r"\small",
        r"\begin{tabular}{c c c}",
        r"\hline",
        (
            r"Threshold $E_{\mathrm{th}}$ [eV] & "
            r"Piecewise fit [$\mathrm{s}^{-1}\,\mathrm{km}^{-2}$] & "
            r"CSV-truncated reference [$\mathrm{s}^{-1}\,\mathrm{km}^{-2}$] \\"
        ),
        r"\hline",
    ]

    for exponent in range(12, 21):
        threshold = 10.0**exponent
        approximation_rate = approx_rate_above_flat_km2(
            threshold, approximation=approximation
        )
        reference_rate = rate_above(threshold, tail_model="truncate")
        rows.append(
            rf"$10^{{{exponent}}}$ & "
            rf"${_tex_number(approximation_rate)}$ & "
            rf"${_tex_number(reference_rate)}$ \\"
        )

    rows.extend([r"\hline", r"\end{tabular}", r"\end{center}", ""])
    RATE_TABLE_TEX.write_text("\n".join(rows), encoding="utf-8")


def main() -> int:
    spectrum = load_spectrum(DEFAULT_CSV)
    approximation = calibrate_piecewise_approximation(
        DEFAULT_CSV,
        breaks_eV=APPROX_BREAKS_EV,
        tail_model="truncate",
    )

    _write_approximation_fragment(approximation)
    _write_rate_table_fragment(approximation)
    make_comparison_plot(
        PLOT_PATH,
        csv_path=DEFAULT_CSV,
        approximation=approximation,
        tail_model="truncate",
    )

    print(f"Dataset rows        : {len(spectrum.energies_eV)}")
    print(f"Dataset SHA-256     : {spectrum.dataset_sha256}")
    print(f"Wrote               : {APPROXIMATION_TEX.name}")
    print(f"Wrote               : {RATE_TABLE_TEX.name}")
    print(f"Wrote               : {PLOT_PATH.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
